[package]
name = "drive_selector"
version = "0.1.0"
authors = ["Glenn Griffin <ggriffiniii@gmail.com>"]
edition = "2018"

[dependencies]
drive_selector_derive = { path = "../drive_selector_derive", "version" = "0.1.0" }
